### ISSUE TITLE
Found error in internal cell when read blif file generated by write_blif command.

### ISSUE THREAD

**Issue by SergeyDegtyar** [YosysHQ/yosys#1473]
## Steps to reproduce the issue
In this case, the reduce_and cell is described.
**test case:**
module top
(
 input [1:0] cin
);

 wire A1;

assign    A1 =  &cin;

endmodule

**script:**
read_verilog bug.v
proc
write_blif blif.blif
design -reset
read_blif blif.blif

## Expected behavior

No errors.

## Actual behavior

ERROR: Found error in internal cell \top.$auto$blifparse.cc:377:parse_blif$81 ($mux) at kernel/rtlil.cc:771:
  cell $mux $auto$blifparse.cc:377:parse_blif$81
    connect \Y $ternary$top.v:22$8_Y
    connect \S \cin
    connect \B $reduce_or$top.v:22$6_Y
    connect \A $reduce_xor$top.v:22$7_Y
  end

**Comment by eddiehung** [comment]
Right now, Yosys requires a few more things for this to work:

```
read_verilog <<EOT
module top
(
input [1:0] cin
);

wire A1;

assign A1 = &cin;

endmodule
EOT

proc
write_blif -param bug1473.blif
dump

design -reset
read_blif -wideports bug1473.blif
```

In particular `write_blif` requires `-param` option so that the `A_SIGNED`, `A_WIDTH` and `Y_WIDTH` parameters that are mandatory for `$reduce_and` (and many other internal cells) are written out.

In addition, since BLIF is a bit-blasted format, multi bit ports have to be recovered using the `read_blif -wideports` switch.
