### ISSUE TITLE
tests: various/plugin.sh fails when PREFIX != /usr/local/share

### ISSUE THREAD

**Issue by Xiretza** [YosysHQ/yosys#1966]
This has already been brought up in https://github.com/YosysHQ/yosys/commit/f11dd6e20838bce1b1fa8e085570d2126484d10f#r38433102, but I'll add it here for better visibility and tracking.

## Steps to reproduce the issue

```
make -j8 PREFIX=/usr/share test
```

## Expected behavior

The tests complete without error.

## Actual behavior

`tests/various/plugin.cc` fails to compile with:

```
plugin.cc:1:10: fatal error: 'kernel/rtlil.h' file not found
#include "kernel/rtlil.h"
         ^~~~~~~~~~~~~~~~
```

This is due to the replacement of include path flags that happens in `plugin.sh`, which assumes `PREFIX=/usr/local/share`.

**Comment by eddiehung** [comment]
Sorry, dropped that previous comment. Thanks for filing, will look at it next week.

**Comment by eddiehung** [comment]
Hi @Xiretza, can you give #1973 a try please?

**Comment by aimylios** [comment]
Unfortunately #1973 has not resolved this issue for me. I'm building nightly yosys RPMs for Fedora, and I get the following error when running the tests:
```
Running plugin.sh..
plugin.cc:1:10: fatal error: kernel/rtlil.h: No such file or directory
    1 | #include "kernel/rtlil.h"
      |          ^~~~~~~~~~~~~~~~
```

I assume this is because the include folder is not specified correctly. `DATDIR` is set to `/usr/share/yosys` (as expected), but in Fedora the include files are located in `/usr/include/yosys`. Consequently, the path substitution `CXXFLAGS=${CXXFLAGS//$DATDIR/..\/..\/share}` does not work (there is no occurence of `DATDIR` in `CXXFLAGS`).

I'm now using the following code in plugin.sh to replace the include path, but there must be a less hacky and more reliable solution to force the local source files to be included.
```
INCDIR=${CXXFLAGS#* -I}
INCDIR=${INCDIR%% -*}
INCDIR=${INCDIR//\//\\\/}
CXXFLAGS=${CXXFLAGS//$INCDIR/..\/..}
```

**Comment by Xiretza** [comment]
How does fedora build its yosys package? From what I can tell that sort of setup isn't supported by the makefile, headers are [always expected to be in `$(DATDIR)/include`](https://github.com/YosysHQ/yosys/blob/bc380b0b56e0fa269a0d5844280cc4419d438d3a/Makefile#L668). If fedora manually patches the makefile or moves the files around after `make install`, it would be their obligation to make sure everything else works as well.

**Comment by aimylios** [comment]
Yes, indeed, Fedora patches the Makefile (see the [SPEC file for 0.9](https://src.fedoraproject.org/rpms/yosys/blob/master/f/yosys.spec) and the [patch](https://src.fedoraproject.org/rpms/yosys/blob/master/f/yosys-cfginc.patch)). If that's the preferred solution, I can of course add another patch to my nightly builds to fix plugin.sh. I just thought there might be a more universal solution to the problem (like the hacky one I posted above).
