### ISSUE TITLE
Parsing error while running the ibex controller example

### ISSUE THREAD

**Issue by Eyantra698Sumanto** [YosysHQ/yosys#3698]
### Version

 Yosys 0.13+15

### On which OS did this happen?

Linux

### Reproduction Steps

Run `make "DESIGN_CONFIG=./designs/asap7/ibex/config.mk"` in the OpenROAD flow scripts.

### Expected Behavior

Yosys should be able to parse all the lines in the [Ibex Controller](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/designs/src/ibex/ibex_controller.v) properly.

### Actual Behavior

Yosys is not able to parse the `function automatic [5:0] sv2v_cast_6; ` line 311 of the [Ibex Controller](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/designs/src/ibex/ibex_controller.v). 

![image](https://user-images.githubusercontent.com/58599984/223676689-67464548-9462-4505-aefd-ffff61e5cfe1.png)

Credits for finding the bug: @Geetima2021

**Comment by jix** [comment]
This syntax is supported starting with yosys 0.8 (released over 4 years ago) and works fine in yosys 0.13 as well as in current releases. It looks like the Makefile is not using the intended yosys version, but a very old version you might have installed separately. I'm not familiar with OpenROAD, but I would guess that you're missing some step to setup your environment so that OpenROAD's yosys is used.

**Comment by Eyantra698Sumanto** [comment]
Okay. Thanks a lot!
