### ISSUE TITLE
Unexpected error is reported in case when use 'bugpoint' command.

### ISSUE THREAD

**Issue by SergeyDegtyar** [YosysHQ/yosys#925]
## Steps to reproduce the issue

Automated test case:
https://github.com/YosysHQ/yosys-tests/tree/master/misc/bugpoint

script:
read_verilog ../top.v
bugpoint

## Expected behavior

Executed successfully

## Actual behavior

+ cd bugpoint/work_bugpoint
+ yosys -ql yosys.log ../../scripts/bugpoint.ys
ERROR: No such command: autoidx (type 'help' for a command overview)
ERROR: No such command: autoidx (type 'help' for a command overview)
ERROR: No such command: autoidx (type 'help' for a command overview)

**Comment by daveshah1** [comment]
The bugpoint pass needs a script to be passed to it, otherwise it is pointless (the purpose is to minimise a design until the minimum design that causes a crash with a given script), the help says:
```
    -script <filename>
        use this script to crash Yosys. required.
```
Nonetheless, I'm tagging this as a bug because we should produce a nice error message when a script isn't given.

**Comment by cliffordwolf** [comment]
cc @whitequark
